### ISSUE TITLE
Question on pos.array

### ISSUE THREAD

**Issue by cqx931** [dhowe/rita4j#16]
js testcases: https://github.com/dhowe/rita2js/blob/master/test/tagger-tests.js#L7
We don't need to support array input for RiTa.pos() for java version, right?

**Comment by dhowe** [comment]
we do need those, but we don't need to support the 'inline' param to RiTa.pos() (in fact we can't because java doesn't allow methods with the same name and different return types as js does)

I've made a few changes to the tagging stuff you checked in, to more closely match the api - let me know if you have questions
