### ISSUE TITLE
Pls check isRhymeProblem in KnownIssues

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita4j#75]
also check if it occurs in js

**Comment by Real-John-Cheung** [comment]
it doesnt occur in js

**Comment by dhowe** [comment]
more cases added, pls check

**Comment by Real-John-Cheung** [comment]
to fix

- [ ] java

- [ ] js

**Comment by Real-John-Cheung** [comment]
@dhowe what rules of rhyme should we applied? because according to the rules in the existing code ( the last vowel (on of after the stress syllable) to the end of the word is the same), solo `s-ow1 l-ow` and yoyo `y-oy1 ow` should rhyme ... (the last vowel after the stress syllable is both `ow`) They do not rhyme according to the wiki definition of rhyme ( "A rhyme is a repetition of similar sounds (usually, exactly the same sound) in the final stressed syllables and any following syllables of two or more words.", [https://en.wikipedia.org/wiki/Rhyme#Perfect_rhymes](url) )  but if we use that rule, some pair in the test would not pass, like solo-tomorrow...

**Comment by dhowe** [comment]
ok, lets leave as is
